### ISSUE TITLE
Testing LDAP?

### ISSUE THREAD

**Issue by asaadhoussam** [ChrisKlug/asp-net-core-integration-testing-demo#1]
thanks to helps
it's great !
Testing with ASP.NET Core including a ldap, it's important too! how can help about this?
thanks

**Comment by ChrisKlug** [comment]
Well, that is much harder, as that requires you talking to a server with LDAP. I can see two ways of doing this. The first is to have a test server with LDAP that you can run against. This would give you the most real scenario. On the other hand, just as with a DB, keeping the directory in the correct state is going to be hard. The second would be to mock that part of the system unfortunately. It won't be as good, but some dependencies just can't be managed properly.
I guess a third option would be to containerize your LDAP service and restart it for every test. But that might be both hard, and a bit slow unfortunately.
Is that an ok answer?

**Comment by buddzbuddy** [comment]
I agree!
