### ISSUE TITLE
Run code after running all the test cases

### ISSUE THREAD

**Issue by akshay-zz** [ChrisKlug/asp-net-core-integration-testing-demo#2]
Hi, thanks for the beautiful post. Just one thing I was trying to achieve. I wanted to run some code after the execution of all the integration test cases.

Actually, I'm trying to spin a database with the help of [testcontainers-dotnet](https://github.com/testcontainers/testcontainers-dotnet) at the start (that you have already mentioned in your post). But also want to dispose it of after running all the test cases.

**Comment by ChrisKlug** [comment]
Hi!
This is something that your test framework should be able to support in some way. I Googled it quickly for xUnit and found this: https://stackoverflow.com/questions/13829737/run-code-once-before-and-after-all-tests-in-xunit-net. There should be some ideas in there. I personally like the suggestion using the assembly level Xunit.TestFramework attribute.

**Comment by akshay-zz** [comment]
Thanks, I have already gone through that thread. Just thought you might have a different approach. Again Thanks
